#
#    Makefile for clangsay
#

install-cows-asciiart:
	@$(MAKE) -C ./asciiart	$@

install-cows-pixelart:
	@$(MAKE) -C ./pixelart	$@

install-cows:			\
	install-cows-asciiart	\
	install-cows-pixelart

.PHONY: install-cows		\
	install-cows-asciiart	\
	install-cows-pixelart
